imports:
    - { resource: "services/form.yml" }
    - { resource: "services/shipping-rules.yml" }
    - { resource: "services/pimcore.yml" }

services:
    _defaults:
        public: true

  # Carrier Validator
    coreshop.shipping.carrier.validator.composite: '@CoreShop\Component\Shipping\Validator\CompositeShippableCarrierValidator'
    CoreShop\Component\Shipping\Validator\ShippableCarrierValidatorInterface: '@CoreShop\Component\Shipping\Validator\CompositeShippableCarrierValidator'
    CoreShop\Component\Shipping\Validator\CompositeShippableCarrierValidator:
        public: false

    # Carrier Processor
    coreshop.carrier.resolver: '@CoreShop\Component\Shipping\Resolver\CarriersResolver'
    CoreShop\Component\Shipping\Resolver\CarriersResolverInterface: '@CoreShop\Component\Shipping\Resolver\CarriersResolver'
    CoreShop\Component\Shipping\Resolver\CarriersResolver:
        arguments:
            - '@coreshop.repository.carrier'
            - '@coreshop.shipping.carrier.validator'

    # Carrier Price Calculator
    coreshop.registry.shipping.price_calculators:
        class: CoreShop\Component\Registry\PrioritizedServiceRegistry
        arguments:
            - CoreShop\Component\Shipping\Calculator\CarrierPriceCalculatorInterface
            - shipping-price-calculators

    coreshop.carrier.price_calculator.shipping_rules: '@CoreShop\Component\Shipping\Calculator\CarrierShippingRulePriceCalculator'
    CoreShop\Component\Shipping\Calculator\CarrierShippingRulePriceCalculator:
        arguments:
            - '@coreshop.carrier.shipping_rule.checker'
            - '@coreshop.carrier.processor.shipping_rules'
        tags:
            - { name: coreshop.shipping.price_calculator, type: shipping-rule, priority: 256 }

    coreshop.carrier.price_calculator: '@CoreShop\Component\Shipping\Calculator\CarrierPriceCalculator'
    CoreShop\Component\Shipping\Calculator\CarrierPriceCalculatorInterface: '@CoreShop\Component\Shipping\Calculator\CarrierPriceCalculator'
    CoreShop\Component\Shipping\Calculator\CarrierPriceCalculator:
        - '@coreshop.registry.shipping.price_calculators'

    coreshop.carrier.price_calculator.default: '@CoreShop\Component\Shipping\Calculator\CompositePriceCalculator'
    CoreShop\Component\Shipping\Calculator\CompositePriceCalculator:
        arguments:
            - ['@CoreShop\Component\Shipping\Calculator\CarrierPriceCalculatorInterface']

    coreshop.shipping.default_resolver.cheapest: '@CoreShop\Component\Shipping\Resolver\CheapestDefaultCarrierResolver'
    CoreShop\Component\Shipping\Resolver\DefaultCarrierResolverInterface: '@CoreShop\Component\Shipping\Resolver\CheapestDefaultCarrierResolver'
    CoreShop\Component\Shipping\Resolver\CheapestDefaultCarrierResolver:
        arguments:
            - '@coreshop.carrier.resolver'
            - '@coreshop.carrier.price_calculator'
