imports:
  - { resource: "services/form.yml" }

services:
  coreshop.registry.shipping_rule.conditions:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - CoreShop\Component\Rule\Condition\ConditionCheckerInterface
      - ShippingRuleCondition

  coreshop.form_registry.shipping_rule.conditions:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  coreshop.registry.shipping_rule.actions:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - CoreShop\Component\Shipping\Rule\Action\CarrierPriceActionProcessorInterface
      - ShippingRuleAction

  coreshop.form_registry.shipping_rule.actions:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  # Shipping Rule Processor
  coreshop.shipping_rule.conditions.processor:
    class: CoreShop\Bundle\RuleBundle\Condition\RuleConditionsValidationProcessor
    shared: false
    arguments:
      - '@coreshop.registry.shipping_rule.conditions'

  coreshop.shipping_rule.processor:
    class: CoreShop\Bundle\RuleBundle\Condition\RuleValidationProcessor
    shared: false
    arguments:
      - '@coreshop.shipping_rule.conditions.processor'

  # Shipping CONDITIONS
  coreshop.shipping_rule.condition.amount:
    class: CoreShop\Component\Shipping\Rule\Condition\AmountConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: amount, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\AmountConfigurationType }

  coreshop.shipping_rule.condition.postcodes:
    class: CoreShop\Component\Shipping\Rule\Condition\PostcodeConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: postcodes, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\PostcodesConfigurationType }

  coreshop.shipping_rule.condition.weight:
    class: CoreShop\Component\Shipping\Rule\Condition\WeightConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: weight, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\WeightConfigurationType }

  coreshop.shipping_rule.condition.dimension:
    class: CoreShop\Component\Shipping\Rule\Condition\DimensionConditionChecker
    tags:
      - { name: coreshop.shipping_rule.condition, type: dimension, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\DimensionConfigurationType }

  coreshop.shipping_rule.condition.nested:
    class: CoreShop\Component\Rule\Condition\NestedConditionChecker
    arguments: ['@coreshop.shipping_rule.conditions.processor']
    tags:
      - { name: coreshop.shipping_rule.condition, type: nested, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\NestedConfigurationType }

  coreshop.shipping_rule.condition.shipping_rule:
    class: CoreShop\Component\Shipping\Rule\Condition\ShippingRuleConditionChecker
    arguments: ['@coreshop.shipping_rule.processor', '@coreshop.repository.shipping_rule']
    tags:
      - { name: coreshop.shipping_rule.condition, type: shippingRule, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Common\ShippingRuleConfigurationType }

  # Shipping Rule ACTIONS
  coreshop.shipping_rule.action.price:
    class: CoreShop\Component\Shipping\Rule\Action\PriceActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: price, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Action\PriceActionConfigurationType }

  coreshop.shipping_rule.action.addition_amount:
    class: CoreShop\Component\Shipping\Rule\Action\AdditionAmountActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: additionAmount, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Action\AdditionAmountActionConfigurationType }

  coreshop.shipping_rule.action.discount_amount:
    class: CoreShop\Component\Shipping\Rule\Action\DiscountAmountActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: discountAmount, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Action\DiscountAmountActionConfigurationType }

  coreshop.shipping_rule.action.addition_percent:
    class: CoreShop\Component\Shipping\Rule\Action\AdditionPercentActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: additionPercent, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Action\AdditionPercentActionConfigurationType }

  coreshop.shipping_rule.action.discount_percent:
    class: CoreShop\Component\Shipping\Rule\Action\DiscountPercentActionProcessor
    tags:
      - { name: coreshop.shipping_rule.action, type: discountPercent, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Action\DiscountPercentActionConfigurationType }

  coreshop.shipping_rule.action.shipping_rule:
    class: CoreShop\Component\Shipping\Rule\Action\ShippingRuleActionProcessor
    arguments: ['@coreshop.carrier.processor.shipping_rules', '@coreshop.repository.shipping_rule']
    tags:
      - { name: coreshop.shipping_rule.action, type: shippingRule, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Common\ShippingRuleConfigurationType}


  coreshop.carrier.processor.shipping_rules:
    class: CoreShop\Bundle\ShippingBundle\Processor\ShippingRuleActionProcessor
    shared: false
    arguments:
      - '@coreshop.registry.shipping_rule.actions'

  # Carrier Shipping Rule Validator
  coreshop.carrier.cart.checker:
    class: CoreShop\Bundle\ShippingBundle\Checker\CarrierShippingRuleChecker
    arguments: ['@coreshop.shipping_rule.processor']

  # Carrier Processor
  coreshop.carrier.cart.processor:
    class: CoreShop\Bundle\ShippingBundle\Processor\CartCarrierProcessor
    arguments: ['@coreshop.repository.carrier', '@coreshop.carrier.cart.checker']

  # Carrier Price Calculator
  coreshop.registry.shipping.price_calculators:
    class: CoreShop\Component\Registry\PrioritizedServiceRegistry
    arguments:
      - CoreShop\Bundle\ShippingBundle\Calculator\CarrierPriceCalculatorInterface
      - shipping-price-calculators

  coreshop.carrier.price_calculator:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CarrierPriceCalculator
    arguments: ['@coreshop.registry.shipping.price_calculators']

  coreshop.carrier.price_calculator.shipping_rules:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CarrierShippingRulePriceCalculator
    arguments:
      - '@coreshop.carrier.cart.checker'
      - '@coreshop.carrier.processor.shipping_rules'
    tags:
      - { name: coreshop.shipping.price_calculator, type: shipping-rule, priority: 256 }

  coreshop.carrier.price_calculator.default:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CompositePriceCalculator
    arguments: [['@coreshop.carrier.price_calculator']]
