services:
    _defaults:
        public: true

    coreshop.pimcore.document.editable.carrier:
        class: CoreShop\Component\Resource\Pimcore\ResourceDocumentTagFactory
        arguments:
            - 'CoreShop\Bundle\ResourceBundle\CoreExtension\Document\Select'
            - 'coreshop.repository.carrier'
            - 'title'
        tags:
            - { name: coreshop.pimcore.document.editable, type: coreshop_carrier }