coreshop_admin_carrier:
  type: coreshop.resources
  resource: |
    alias: coreshop.carrier

coreshop_admin_shipping_rule:
  type: coreshop.resources
  resource: |
    alias: coreshop.shipping_rule

coreshop_admin_shipping_rule_types:
  path: /%coreshop.admin.route.base%/shipping_rules/get-config
  defaults: { _controller: 'coreshop.admin_controller.shipping_rule:getConfigAction'}