# https://docs.coreshop.org/2.1.0/Bundles/Resource_Bundle/CustomEntities.html
# If you want to add additional routes
# - Add a new Controller which extends ResourceController
# - Change the DI Configuration: CoreShop/Bundle/ShippingBundle/DependencyInjection/Configuration.php
coreshop_admin_carrier:
    type: coreshop.resources
    resource: |
      alias: coreshop.carrier
      additional_routes:
        config:
          path: get-config
          action: getConfig
          methods:
            - GET

coreshop_admin_shipping_rule:
    type: coreshop.resources
    resource: |
      alias: coreshop.shipping_rule
      additional_routes:
        config:
          path: get-config
          action: getConfig
          methods:
            - GET
