CoreShop\Component\Shipping\Model\Carrier:
    properties:
        identifier:
            - NotBlank: { groups: [coreshop] }
        isFree:
            - Type: { type: boolean }
        hideFromCheckout:
            - Type: { type: boolean }
